// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Yolla.Infrastructure.Persistence;

#nullable disable

namespace Yolla.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(YollaDbContext))]
    [Migration("20260820095402_Bildirimler")]
    partial class Bildirimler
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("Yolla.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Icon")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("key");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name_tr");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<short>("Weight")
                        .HasColumnType("smallint")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_key");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_categories_parent_id");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "landmark",
                            IsVisible = true,
                            Key = "historic",
                            NameEn = "History",
                            NameTr = "Tarihi",
                            Weight = (short)0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "palette",
                            IsVisible = true,
                            Key = "culture",
                            NameEn = "Culture & Arts",
                            NameTr = "Kültür & Sanat",
                            Weight = (short)0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "tree",
                            IsVisible = true,
                            Key = "nature",
                            NameEn = "Nature",
                            NameTr = "Doğa",
                            Weight = (short)0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "mosque",
                            IsVisible = true,
                            Key = "religious",
                            NameEn = "Religious",
                            NameTr = "İnanç",
                            Weight = (short)0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "ferris-wheel",
                            IsVisible = true,
                            Key = "entertainment",
                            NameEn = "Entertainment",
                            NameTr = "Eğlence",
                            Weight = (short)0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "map-pin",
                            IsVisible = true,
                            Key = "other",
                            NameEn = "Other",
                            NameTr = "Diğer",
                            Weight = (short)0
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "castle",
                            IsVisible = true,
                            Key = "castle",
                            NameEn = "Castle",
                            NameTr = "Kale",
                            ParentId = 1,
                            Weight = (short)10
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "columns",
                            IsVisible = true,
                            Key = "ruins",
                            NameEn = "Ruins",
                            NameTr = "Ören Yeri",
                            ParentId = 1,
                            Weight = (short)9
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "columns",
                            IsVisible = true,
                            Key = "archaeological_site",
                            NameEn = "Archaeological Site",
                            NameTr = "Antik Kent",
                            ParentId = 1,
                            Weight = (short)10
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "monument",
                            IsVisible = true,
                            Key = "monument",
                            NameEn = "Monument",
                            NameTr = "Anıt",
                            ParentId = 1,
                            Weight = (short)7
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "building",
                            IsVisible = true,
                            Key = "historic_building",
                            NameEn = "Historic Building",
                            NameTr = "Tarihi Yapı",
                            ParentId = 1,
                            Weight = (short)8
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "bridge",
                            IsVisible = true,
                            Key = "historic_bridge",
                            NameEn = "Historic Bridge",
                            NameTr = "Tarihi Köprü",
                            ParentId = 1,
                            Weight = (short)7
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "landmark",
                            IsVisible = true,
                            Key = "tomb",
                            NameEn = "Tomb",
                            NameTr = "Türbe",
                            ParentId = 1,
                            Weight = (short)6
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "warehouse",
                            IsVisible = true,
                            Key = "caravanserai",
                            NameEn = "Caravanserai",
                            NameTr = "Kervansaray",
                            ParentId = 1,
                            Weight = (short)9
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "tower",
                            IsVisible = true,
                            Key = "tower",
                            NameEn = "Tower",
                            NameTr = "Kule",
                            ParentId = 1,
                            Weight = (short)7
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "swords",
                            IsVisible = true,
                            Key = "battlefield",
                            NameEn = "Battlefield",
                            NameTr = "Savaş Alanı",
                            ParentId = 1,
                            Weight = (short)9
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "museum",
                            IsVisible = true,
                            Key = "museum",
                            NameEn = "Museum",
                            NameTr = "Müze",
                            ParentId = 2,
                            Weight = (short)10
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "image",
                            IsVisible = true,
                            Key = "gallery",
                            NameEn = "Art Gallery",
                            NameTr = "Sanat Galerisi",
                            ParentId = 2,
                            Weight = (short)7
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "drama",
                            IsVisible = true,
                            Key = "theatre",
                            NameEn = "Theatre",
                            NameTr = "Tiyatro",
                            ParentId = 2,
                            Weight = (short)6
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "brush",
                            IsVisible = true,
                            Key = "artwork",
                            NameEn = "Artwork",
                            NameTr = "Sanat Eseri",
                            ParentId = 2,
                            Weight = (short)4
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "umbrella",
                            IsVisible = true,
                            Key = "beach",
                            NameEn = "Beach",
                            NameTr = "Plaj",
                            ParentId = 3,
                            Weight = (short)9
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "waves",
                            IsVisible = true,
                            Key = "waterfall",
                            NameEn = "Waterfall",
                            NameTr = "Şelale",
                            ParentId = 3,
                            Weight = (short)10
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "mountain",
                            IsVisible = true,
                            Key = "cave",
                            NameEn = "Cave",
                            NameTr = "Mağara",
                            ParentId = 3,
                            Weight = (short)9
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "trees",
                            IsVisible = true,
                            Key = "national_park",
                            NameEn = "National Park",
                            NameTr = "Milli Park",
                            ParentId = 3,
                            Weight = (short)10
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "binoculars",
                            IsVisible = true,
                            Key = "viewpoint",
                            NameEn = "Viewpoint",
                            NameTr = "Manzara Noktası",
                            ParentId = 3,
                            Weight = (short)8
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "droplet",
                            IsVisible = true,
                            Key = "lake",
                            NameEn = "Lake",
                            NameTr = "Göl",
                            ParentId = 3,
                            Weight = (short)8
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "hot-tub",
                            IsVisible = true,
                            Key = "hot_spring",
                            NameEn = "Hot Spring",
                            NameTr = "Kaplıca",
                            ParentId = 3,
                            Weight = (short)8
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "mountain-snow",
                            IsVisible = true,
                            Key = "valley",
                            NameEn = "Valley & Canyon",
                            NameTr = "Vadi & Kanyon",
                            ParentId = 3,
                            Weight = (short)8
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "palmtree",
                            IsVisible = true,
                            Key = "island",
                            NameEn = "Island",
                            NameTr = "Ada",
                            ParentId = 3,
                            Weight = (short)7
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "tree-deciduous",
                            IsVisible = true,
                            Key = "park",
                            NameEn = "Park",
                            NameTr = "Park",
                            ParentId = 3,
                            Weight = (short)4
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "bird",
                            IsVisible = true,
                            Key = "wetland",
                            NameEn = "Wetland",
                            NameTr = "Sulak Alan",
                            ParentId = 3,
                            Weight = (short)7
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "mosque",
                            IsVisible = true,
                            Key = "mosque",
                            NameEn = "Mosque",
                            NameTr = "Cami",
                            ParentId = 4,
                            Weight = (short)6
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "church",
                            IsVisible = true,
                            Key = "church",
                            NameEn = "Church",
                            NameTr = "Kilise",
                            ParentId = 4,
                            Weight = (short)8
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "star-of-david",
                            IsVisible = true,
                            Key = "synagogue",
                            NameEn = "Synagogue",
                            NameTr = "Sinagog",
                            ParentId = 4,
                            Weight = (short)8
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "church",
                            IsVisible = true,
                            Key = "monastery",
                            NameEn = "Monastery",
                            NameTr = "Manastır",
                            ParentId = 4,
                            Weight = (short)9
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "ferris-wheel",
                            IsVisible = true,
                            Key = "theme_park",
                            NameEn = "Theme Park",
                            NameTr = "Tema Parkı",
                            ParentId = 5,
                            Weight = (short)7
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "paw-print",
                            IsVisible = true,
                            Key = "zoo",
                            NameEn = "Zoo",
                            NameTr = "Hayvanat Bahçesi",
                            ParentId = 5,
                            Weight = (short)7
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "fish",
                            IsVisible = true,
                            Key = "aquarium",
                            NameEn = "Aquarium",
                            NameTr = "Akvaryum",
                            ParentId = 5,
                            Weight = (short)7
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "waves",
                            IsVisible = true,
                            Key = "water_park",
                            NameEn = "Water Park",
                            NameTr = "Su Parkı",
                            ParentId = 5,
                            Weight = (short)6
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "shopping-bag",
                            IsVisible = true,
                            Key = "bazaar",
                            NameEn = "Bazaar",
                            NameTr = "Çarşı & Pazar",
                            ParentId = 6,
                            Weight = (short)7
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "utensils",
                            IsVisible = true,
                            Key = "picnic_site",
                            NameEn = "Picnic Site",
                            NameTr = "Piknik Alanı",
                            ParentId = 6,
                            Weight = (short)3
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Icon = "map-pin",
                            IsVisible = true,
                            Key = "other_poi",
                            NameEn = "Other",
                            NameTr = "Diğer",
                            ParentId = 6,
                            Weight = (short)2
                        },
                        new
                        {
                            Id = 90,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsVisible = false,
                            Key = "accommodation",
                            NameEn = "Accommodation",
                            NameTr = "Konaklama",
                            ParentId = 6,
                            Weight = (short)0
                        },
                        new
                        {
                            Id = 91,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsVisible = false,
                            Key = "tourist_information",
                            NameEn = "Tourist Information",
                            NameTr = "Turizm Bürosu",
                            ParentId = 6,
                            Weight = (short)0
                        },
                        new
                        {
                            Id = 92,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsVisible = false,
                            Key = "camp_site",
                            NameEn = "Camp Site",
                            NameTr = "Kamp Alanı",
                            ParentId = 6,
                            Weight = (short)0
                        });
                });

            modelBuilder.Entity("Yolla.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Geometry>("Boundary")
                        .HasColumnType("geometry (Geometry, 4326)")
                        .HasColumnName("boundary");

                    b.Property<Point>("Center")
                        .IsRequired()
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("center");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("NameEn")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name_normalized");

                    b.Property<long?>("OsmRelationId")
                        .HasColumnType("bigint")
                        .HasColumnName("osm_relation_id");

                    b.Property<int?>("Population")
                        .HasColumnType("integer")
                        .HasColumnName("population");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.HasIndex("Boundary")
                        .HasDatabaseName("ix_cities_boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "gist");

                    b.HasIndex("Center")
                        .HasDatabaseName("ix_cities_center");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Center"), "gist");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_cities_country_id");

                    b.HasIndex("NameNormalized")
                        .HasDatabaseName("ix_cities_name_normalized");

                    b.HasIndex("OsmRelationId")
                        .IsUnique()
                        .HasDatabaseName("ix_cities_osm_relation_id")
                        .HasFilter("osm_relation_id IS NOT NULL");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_cities_slug");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("Yolla.Domain.Entities.CoinEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("note");

                    b.Property<int?>("PhotoSubmissionId")
                        .HasColumnType("integer")
                        .HasColumnName("photo_submission_id");

                    b.Property<int?>("PlaceSuggestionId")
                        .HasColumnType("integer")
                        .HasColumnName("place_suggestion_id");

                    b.Property<int?>("PremiumGrantId")
                        .HasColumnType("integer")
                        .HasColumnName("premium_grant_id");

                    b.Property<int>("Reason")
                        .HasColumnType("integer")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_coin_entries");

                    b.HasIndex("PhotoSubmissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_coin_entries_photo_submission_id")
                        .HasFilter("photo_submission_id IS NOT NULL");

                    b.HasIndex("PlaceSuggestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_coin_entries_place_suggestion_id")
                        .HasFilter("place_suggestion_id IS NOT NULL");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_coin_entries_user_id_created_at");

                    b.ToTable("coin_entries", (string)null);
                });

            modelBuilder.Entity("Yolla.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Iso2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("iso2");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_tr");

                    b.Property<long?>("OsmRelationId")
                        .HasColumnType("bigint")
                        .HasColumnName("osm_relation_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.HasIndex("Iso2")
                        .IsUnique()
                        .HasDatabaseName("ix_countries_iso2");

                    b.ToTable("countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Iso2 = "TR",
                            NameEn = "Türkiye",
                            NameTr = "Türkiye",
                            OsmRelationId = 174737L
                        });
                });

            modelBuilder.Entity("Yolla.Domain.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppVersion")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("app_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("device_uuid");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("platform");

                    b.Property<string>("PushToken")
                        .HasColumnType("text")
                        .HasColumnName("push_token");

                    b.Property<DateTimeOffset?>("PushTokenUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("push_token_updated_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("DeviceUuid")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_device_uuid");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_devices_user_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("Yolla.Domain.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Geometry>("Boundary")
                        .HasColumnType("geometry (Geometry, 4326)")
                        .HasColumnName("boundary");

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name_normalized");

                    b.Property<long?>("OsmRelationId")
                        .HasColumnType("bigint")
                        .HasColumnName("osm_relation_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_districts");

                    b.HasIndex("Boundary")
                        .HasDatabaseName("ix_districts_boundary");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Boundary"), "gist");

                    b.HasIndex("OsmRelationId")
                        .IsUnique()
                        .HasDatabaseName("ix_districts_osm_relation_id")
                        .HasFilter("osm_relation_id IS NOT NULL");

                    b.HasIndex("CityId", "NameNormalized")
                        .HasDatabaseName("ix_districts_city_id_name_normalized");

                    b.ToTable("districts", (string)null);
                });

            modelBuilder.Entity("Yolla.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("place_id");

                    b.Property<DateTimeOffset?>("PushedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pushed_at");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id")
                        .HasFilter("read_at IS NULL");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_user_id_created_at");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Yolla.Domain.Entities.PhotoSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoinsAwarded")
                        .HasColumnType("integer")
                        .HasColumnName("coins_awarded");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<int?>("PlaceContributionId")
                        .HasColumnType("integer")
                        .HasColumnName("place_contribution_id");

                    b.Property<int>("PlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("place_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("storage_path");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_photo_submissions");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("ix_photo_submissions_place_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_photo_submissions_status_created_at");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_photo_submissions_user_id_status");

                    b.ToTable("photo_submissions", (string)null);
                });

            modelBuilder.Entity("Yolla.Domain.Entities.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("address");

                    b.Property<short?>("AvgVisitMinutes")
                        .HasColumnType("smallint")
                        .HasColumnName("avg_visit_minutes");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<string>("CommonsRef")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("commons_ref");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text")
                        .HasColumnName("description_en");

                    b.Property<string>("DescriptionTr")
                        .HasColumnType("text")
                        .HasColumnName("description_tr");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("district_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<string>("NameEn")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name_en");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("opening_hours");

                    b.Property<long>("OsmId")
                        .HasColumnType("bigint")
                        .HasColumnName("osm_id");

                    b.Property<int>("OsmType")
                        .HasColumnType("integer")
                        .HasColumnName("osm_type");

                    b.Property<string>("PhotoAuthor")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("photo_author");

                    b.Property<string>("PhotoLicense")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("photo_license");

                    b.Property<string>("PhotoSource")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("photo_source");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("photo_url");

                    b.Property<short>("QualityScore")
                        .HasColumnType("smallint")
                        .HasColumnName("quality_score");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.Property<string>("WikidataId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("wikidata_id");

                    b.Property<string>("WikipediaTitle")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("wikipedia_title");

                    b.HasKey("Id")
                        .HasName("pk_places");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_places_category_id");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_places_country_id");

                    b.HasIndex("DistrictId")
                        .HasDatabaseName("ix_places_district_id");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_places_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("Slug")
                        .HasDatabaseName("ix_places_slug");

                    b.HasIndex("CityId", "QualityScore")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_places_city_id_quality_score");

                    b.HasIndex("OsmType", "OsmId")
                        .IsUnique()
                        .HasDatabaseName("ix_places_osm_type_osm_id");

                    b.ToTable("places", (string)null);
                });

            modelBuilder.Entity("Yolla.Domain.Entities.PlaceContribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("author");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language");

                    b.Property<string>("License")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("license");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<int>("PlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("place_id");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("source_url");

                    b.Property<string>("SubmittedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("submitted_by");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_place_contributions");

                    b.HasIndex("PlaceId", "Type", "Language")
                        .HasDatabaseName("ix_place_contributions_place_id_type_language");

                    b.ToTable("place_contributions", (string)null);
                });

            modelBuilder.Entity("Yolla.Domain.Entities.PlaceSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("address");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<int?>("CoinsAwarded")
                        .HasColumnType("integer")
                        .HasColumnName("coins_awarded");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("integer")
                        .HasColumnName("district_id");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("place_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_place_suggestions");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_place_suggestions_category_id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_place_suggestions_city_id");

                    b.HasIndex("DistrictId")
                        .HasDatabaseName("ix_place_suggestions_district_id");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_place_suggestions_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("ix_place_suggestions_place_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_place_suggestions_status_created_at");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_place_suggestions_user_id_status");

                    b.ToTable("place_suggestions", (string)null);
                });

            modelBuilder.Entity("Yolla.Domain.Entities.PlaceTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<int>("PlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("place_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_place_translations");

                    b.HasIndex("PlaceId", "Language")
                        .IsUnique()
                        .HasDatabaseName("ix_place_translations_place_id_language");

                    b.ToTable("place_translations", (string)null);
                });

            modelBuilder.Entity("Yolla.Domain.Entities.PremiumGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoinsSpent")
                        .HasColumnType("integer")
                        .HasColumnName("coins_spent");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("note");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_premium_grants");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_premium_grants_user_id_expires_at");

                    b.ToTable("premium_grants", (string)null);
                });

            modelBuilder.Entity("Yolla.Domain.Entities.Swipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Context")
                        .HasColumnType("integer")
                        .HasColumnName("context");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<int>("PlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("place_id");

                    b.Property<int?>("TripId")
                        .HasColumnType("integer")
                        .HasColumnName("trip_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_swipes");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("ix_swipes_place_id");

                    b.HasIndex("DeviceId", "PlaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_swipes_device_id_place_id");

                    b.ToTable("swipes", (string)null);
                });

            modelBuilder.Entity("Yolla.Domain.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<int>("CorridorBufferMeters")
                        .HasColumnType("integer")
                        .HasColumnName("corridor_buffer_meters");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer")
                        .HasColumnName("device_id");

                    b.Property<Point>("EndPoint")
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("end_point");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("RouteGeometry")
                        .HasColumnType("text")
                        .HasColumnName("route_geometry");

                    b.Property<Point>("StartPoint")
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("start_point");

                    b.Property<double?>("TotalDistanceMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("total_distance_meters");

                    b.Property<double?>("TotalDurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("total_duration_seconds");

                    b.Property<int>("TravelMode")
                        .HasColumnType("integer")
                        .HasColumnName("travel_mode");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_trips");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_trips_city_id");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_trips_device_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_trips_user_id");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("Yolla.Domain.Entities.TripPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayIndex")
                        .HasColumnType("integer")
                        .HasColumnName("day_index");

                    b.Property<bool>("IsVisited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visited");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<int>("PlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("place_id");

                    b.Property<int>("TripId")
                        .HasColumnType("integer")
                        .HasColumnName("trip_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_trip_places");

                    b.HasIndex("PlaceId")
                        .HasDatabaseName("ix_trip_places_place_id");

                    b.HasIndex("TripId", "PlaceId")
                        .IsUnique()
                        .HasDatabaseName("ix_trip_places_trip_id_place_id");

                    b.ToTable("trip_places", (string)null);
                });

            modelBuilder.Entity("Yolla.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Yolla.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Yolla.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Yolla.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Yolla.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("Yolla.Domain.Entities.Category", b =>
                {
                    b.HasOne("Yolla.Domain.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Yolla.Domain.Entities.City", b =>
                {
                    b.HasOne("Yolla.Domain.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cities_countries_country_id");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Yolla.Domain.Entities.District", b =>
                {
                    b.HasOne("Yolla.Domain.Entities.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_districts_cities_city_id");

                    b.Navigation("City");
                });

            modelBuilder.Entity("Yolla.Domain.Entities.PhotoSubmission", b =>
                {
                    b.HasOne("Yolla.Domain.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_photo_submissions_places_place_id");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Yolla.Domain.Entities.Place", b =>
                {
                    b.HasOne("Yolla.Domain.Entities.Category", "Category")
                        .WithMany("Places")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_places_categories_category_id");

                    b.HasOne("Yolla.Domain.Entities.City", "City")
                        .WithMany("Places")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_places_cities_city_id");

                    b.HasOne("Yolla.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_places_countries_country_id");

                    b.HasOne("Yolla.Domain.Entities.District", "District")
                        .WithMany("Places")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_places_districts_district_id");

                    b.Navigation("Category");

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("District");
                });

            modelBuilder.Entity("Yolla.Domain.Entities.PlaceContribution", b =>
                {
                    b.HasOne("Yolla.Domain.Entities.Place", "Place")
                        .WithMany("Contributions")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_place_contributions_places_place_id");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Yolla.Domain.Entities.PlaceSuggestion", b =>
                {
                    b.HasOne("Yolla.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_place_suggestions_categories_category_id");

                    b.HasOne("Yolla.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_place_suggestions_cities_city_id");

                    b.HasOne("Yolla.Domain.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_place_suggestions_districts_district_id");

                    b.HasOne("Yolla.Domain.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_place_suggestions_places_place_id");

                    b.Navigation("Category");

                    b.Navigation("City");

                    b.Navigation("District");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Yolla.Domain.Entities.PlaceTranslation", b =>
                {
                    b.HasOne("Yolla.Domain.Entities.Place", "Place")
                        .WithMany("Translations")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_place_translations_places_place_id");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Yolla.Domain.Entities.Swipe", b =>
                {
                    b.HasOne("Yolla.Domain.Entities.Device", "Device")
                        .WithMany("Swipes")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_swipes_devices_device_id");

                    b.HasOne("Yolla.Domain.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_swipes_places_place_id");

                    b.Navigation("Device");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Yolla.Domain.Entities.Trip", b =>
                {
                    b.HasOne("Yolla.Domain.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_trips_cities_city_id");

                    b.HasOne("Yolla.Domain.Entities.Device", "Device")
                        .WithMany("Trips")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trips_devices_device_id");

                    b.Navigation("City");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Yolla.Domain.Entities.TripPlace", b =>
                {
                    b.HasOne("Yolla.Domain.Entities.Place", "Place")
                        .WithMany()
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trip_places_places_place_id");

                    b.HasOne("Yolla.Domain.Entities.Trip", "Trip")
                        .WithMany("Places")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trip_places_trips_trip_id");

                    b.Navigation("Place");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Yolla.Domain.Entities.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Places");
                });

            modelBuilder.Entity("Yolla.Domain.Entities.City", b =>
                {
                    b.Navigation("Districts");

                    b.Navigation("Places");
                });

            modelBuilder.Entity("Yolla.Domain.Entities.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Yolla.Domain.Entities.Device", b =>
                {
                    b.Navigation("Swipes");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("Yolla.Domain.Entities.District", b =>
                {
                    b.Navigation("Places");
                });

            modelBuilder.Entity("Yolla.Domain.Entities.Place", b =>
                {
                    b.Navigation("Contributions");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Yolla.Domain.Entities.Trip", b =>
                {
                    b.Navigation("Places");
                });
#pragma warning restore 612, 618
        }
    }
}
